### ISSUE TITLE
Warning on Elixir v1.14

### ISSUE THREAD

**Issue by thbar** [elixir-mint/hpax#11]
I'm doing a bit of preliminary testing with https://github.com/elixir-lang/elixir/releases/tag/v1.14.0-rc.1, and noticed the following warning, so I'm opening an issue to report it :

```
==> hpax
Compiling 4 files (.ex)
warning: use Bitwise is deprecated. import Bitwise instead
  lib/hpax/huffman.ex:4: HPAX.Huffman

warning: use Bitwise is deprecated. import Bitwise instead
  lib/hpax/types.ex:4: HPAX.Types

Generated hpax app
```

Happy to provide a PR if you want.

**Comment by ericmj** [comment]
A PR would be very appreciated.

**Comment by thbar** [comment]
Good news: it has already been fixed in https://github.com/elixir-mint/hpax/pull/8 (my dependencies were not fully up-to-date), as I discovered while running the tests locally.

It is just not released yet (https://github.com/elixir-mint/hpax/compare/v0.1.1...7308c09415cdb1c773563e8cd539f29e0a316aab).

Do you prefer to leave the issue open as a reminder to publish a release maybe?

**Comment by ericmj** [comment]
I have published a new release.
