### ISSUE TITLE
Compile warning on `HPAX.Table.lookup_by_index/2`

### ISSUE THREAD

**Issue by Saveljeffjonatan** [elixir-mint/hpax#17]
HPAX version: "0.2.0",

Reason for issue: In order to stop the compiler to complain about the warning stated below, we should update the function `lookup_by_index/2` to have a specific step size defined within the range guard clause. It is more idiomatic when dealing with ranges in guards, as it makes the step size clear.

  Warning: 
  `warning: 62..@dynamic_table_start + length - 1 inside guards requires an explicit step, please write 62..@dynamic_table_start + length - 1//1 or 62..@dynamic_table_start + length - 1//-1 instead`

Old code to be changed:
- [lib/hpax/table.ex:160](https://github.com/elixir-mint/hpax/blob/46fece83ea6f7c5c5efa4d6a892a5e28f932b1d0/lib/hpax/table.ex#L159C1-L162C6)
`def lookup_by_index(%__MODULE__{entries: entries, length: length}, index)
     when index >= @dynamic_table_start and index <= @dynamic_table_start + length - 1 do
    {:ok, Enum.at(entries, index - @dynamic_table_start)}
  end
`

Changed code:
 `def lookup_by_index(%__MODULE__{entries: entries, length: length}, index)
      when index in @dynamic_table_start..(@dynamic_table_start + length - 1)//1 do
    {:ok, Enum.at(entries, index - @dynamic_table_start)}
  end`

**Comment by Saveljeffjonatan** [comment]
I tried to open a pull requests but can't as per permissions.

**Comment by whatyouhide** [comment]
Hi @Saveljeffjonatan, I’m a bit confused because HPAX 1.0.0 (https://hex.pm/packages/hpax) has been out for a couple months now, and this warning is fixed in there?

**Comment by Saveljeffjonatan** [comment]
I am using a default phoenix project since a few weeks. I will dig in and see where the base deps is coming from.

**Comment by whatyouhide** [comment]
Yeah, likely something hasnt updated. I will close this issue as it's not an issue with HPAX, but feel free to open another issue in the appropriate repo once you find something.

**Comment by Saveljeffjonatan** [comment]
Yes, will do. Thanks for the response!

**Comment by Saveljeffjonatan** [comment]
Just for reference, seems like my cache on github was broken and hadn't updated `bandit http server` package since 3 weeks ago. *They introduced hpax ~> 1.0.0 but mine was locked at 0.2.0.

Thanks for the assitance once again
worm regards
