### ISSUE TITLE
`HPax.encode/2` should accept bare keyword lists

### ISSUE THREAD

**Issue by mtrudel** [elixir-mint/hpax#4]
`HPax.encode/2` requires three-element tuples to be passed, where the first element of each tuple describes the encoding action to be applied (one of `:store`, `:store_name`, `:no_store`, `:never_store`). In all existing call sites in both Mint and bandit, these actions are always the same. I propose an `HPax.encode/3` which takes a third argument containing the action type to apply to all entries, which would allow calling with a standard keyword list of headers as the second argument.

Opening the issue for discussion in advance of a pretty trivial, as it will also influence call-site refactors in both Mint and bandit.

**Comment by whatyouhide** [comment]
Added!
